/**
 * Static curated fallback data for when external APIs (AniList, Jikan/MAL) are down.
 * All images are sourced from CDNs that don't require auth.
 */

export interface StaticAnime {
  mal_id: number;
  title: string;
  title_english: string;
  title_japanese: string;
  images: {
    jpg: { image_url: string; large_image_url: string };
    webp: { image_url: string; large_image_url: string };
  };
  bannerImage?: string;
  type: string;
  source: string;
  episodes: number | null;
  status: string;
  airing: boolean;
  aired: { string: string; from: string | null; to: string | null };
  duration: string;
  rating: string;
  score: number;
  scored_by: number;
  rank: number;
  popularity: number;
  synopsis: string;
  genres: { mal_id: number; name: string }[];
  year: number;
}

export const TOP_ANIME_STATIC: StaticAnime[] = [
  {
    mal_id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    title_english: 'Fullmetal Alchemist: Brotherhood',
    title_japanese: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-t2RBIoZQuWXl.jpg',
    type: 'TV', source: 'Manga', episodes: 64, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 2009 – Jul 2010', from: '2009-04-05', to: '2010-07-04' },
    duration: '24 min per ep', rating: 'R - 17+',
    score: 9.11, scored_by: 2200000, rank: 1, popularity: 3,
    synopsis: 'Two brothers search for a Philosopher\'s Stone after an attempt to revive their deceased mother goes awry, leaving them in damaged physical forms.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 8, name: 'Drama' }, { mal_id: 10, name: 'Fantasy' }],
    year: 2009,
  },
  {
    mal_id: 9253,
    title: 'Steins;Gate',
    title_english: 'Steins;Gate',
    title_japanese: 'シュタインズ・ゲート',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/5/73199.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/5/73199.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/9253-JNFrezb0QDNO.jpg',
    type: 'TV', source: 'Visual novel', episodes: 24, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 2011 – Sep 2011', from: '2011-04-06', to: '2011-09-14' },
    duration: '23 min per ep', rating: 'PG-13',
    score: 9.07, scored_by: 1900000, rank: 2, popularity: 4,
    synopsis: 'A self-proclaimed mad scientist stumbles upon a form of time travel using his microwave, catapulting him into a spiral of cause and effect.',
    genres: [{ mal_id: 3, name: 'Sci-Fi' }, { mal_id: 29, name: 'Psychological' }, { mal_id: 41, name: 'Thriller' }, { mal_id: 8, name: 'Drama' }],
    year: 2011,
  },
  {
    mal_id: 11061,
    title: 'Hunter x Hunter (2011)',
    title_english: 'Hunter x Hunter (2011)',
    title_japanese: 'HUNTER×HUNTER（2011）',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-HSSH2W2QQQIX.jpg',
    type: 'TV', source: 'Manga', episodes: 148, status: 'Finished Airing', airing: false,
    aired: { string: 'Oct 2011 – Sep 2014', from: '2011-10-02', to: '2014-09-24' },
    duration: '23 min per ep', rating: 'PG-13',
    score: 9.04, scored_by: 1800000, rank: 3, popularity: 7,
    synopsis: 'Gon Freecss aspires to become a Hunter to find his missing father. With his friends, he navigates a world of hunters, monsters, and mysteries.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    year: 2011,
  },
  {
    mal_id: 16498,
    title: 'Attack on Titan',
    title_english: 'Attack on Titan',
    title_japanese: '進撃の巨人',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8ZepHyFxKlzh.jpg',
    type: 'TV', source: 'Manga', episodes: 25, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 2013 – Sep 2013', from: '2013-04-07', to: '2013-09-29' },
    duration: '24 min per ep', rating: 'R - 17+',
    score: 8.53, scored_by: 2900000, rank: 6, popularity: 1,
    synopsis: 'Eren Yeager swears to destroy the Titans after his mother is devoured. He joins the military and discovers the truth about their world.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 8, name: 'Drama' }, { mal_id: 10, name: 'Fantasy' }],
    year: 2013,
  },
  {
    mal_id: 1535,
    title: 'Death Note',
    title_english: 'Death Note',
    title_japanese: 'デスノート',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/9/9453.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/9/9453l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/9/9453.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/9/9453l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535-T7eyFsgcmKbx.jpg',
    type: 'TV', source: 'Manga', episodes: 37, status: 'Finished Airing', airing: false,
    aired: { string: 'Oct 2006 – Jun 2007', from: '2006-10-04', to: '2007-06-27' },
    duration: '23 min per ep', rating: 'R - 17+',
    score: 8.62, scored_by: 3400000, rank: 5, popularity: 2,
    synopsis: 'Light Yagami discovers a supernatural notebook and gains the power to kill anyone whose name he writes in it, setting himself up as the god of a new world.',
    genres: [{ mal_id: 29, name: 'Psychological' }, { mal_id: 26, name: 'Supernatural' }, { mal_id: 24, name: 'Mystery' }],
    year: 2006,
  },
  {
    mal_id: 40748,
    title: 'Jujutsu Kaisen',
    title_english: 'Jujutsu Kaisen',
    title_japanese: '呪術廻戦',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-w7PxGzrLDHnR.jpg',
    type: 'TV', source: 'Manga', episodes: 24, status: 'Finished Airing', airing: false,
    aired: { string: 'Oct 2020 – Mar 2021', from: '2020-10-03', to: '2021-03-27' },
    duration: '23 min per ep', rating: 'R - 17+',
    score: 8.72, scored_by: 1800000, rank: 4, popularity: 5,
    synopsis: 'Yuji Itadori joins a secret organization of Jujutsu Sorcerers to eliminate powerful Cursed Spirits that threaten society.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 10, name: 'Fantasy' }, { mal_id: 25, name: 'Shounen' }],
    year: 2020,
  },
  {
    mal_id: 21,
    title: 'One Piece',
    title_english: 'One Piece',
    title_japanese: 'ワンピース',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/6/73245.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/6/73245l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/6/73245.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/6/73245l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-YzxhLRxXMYNm.jpg',
    type: 'TV', source: 'Manga', episodes: null, status: 'Currently Airing', airing: true,
    aired: { string: 'Oct 1999 – ?', from: '1999-10-20', to: null },
    duration: '24 min per ep', rating: 'PG-13',
    score: 8.72, scored_by: 1200000, rank: 11, popularity: 10,
    synopsis: 'Monkey D. Luffy sets out to become King of the Pirates by finding the legendary One Piece treasure in a world of adventure on the high seas.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 4, name: 'Comedy' }, { mal_id: 10, name: 'Fantasy' }],
    year: 1999,
  },
  {
    mal_id: 38000,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    title_english: 'Demon Slayer: Kimetsu no Yaiba',
    title_japanese: '鬼滅の刃',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-EUFOU1KD5vJE.jpg',
    type: 'TV', source: 'Manga', episodes: 26, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 2019 – Sep 2019', from: '2019-04-06', to: '2019-09-28' },
    duration: '23 min per ep', rating: 'R - 17+',
    score: 8.57, scored_by: 2200000, rank: 8, popularity: 8,
    synopsis: 'Tanjiro Kamado, after his family is slaughtered by a demon, becomes a demon slayer to cure his sister Nezuko and avenge his family.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 10, name: 'Fantasy' }, { mal_id: 25, name: 'Shounen' }],
    year: 2019,
  },
  {
    mal_id: 2904,
    title: 'Code Geass: Lelouch of the Rebellion',
    title_english: 'Code Geass: Lelouch of the Rebellion',
    title_japanese: 'コードギアス 反逆のルルーシュ',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/5/50331.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/5/50331l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/5/50331.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/5/50331l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/2904-kCFLzJanLLsZ.jpg',
    type: 'TV', source: 'Original', episodes: 25, status: 'Finished Airing', airing: false,
    aired: { string: 'Oct 2006 – Jul 2007', from: '2006-10-06', to: '2007-07-29' },
    duration: '23 min per ep', rating: 'R - 17+',
    score: 8.71, scored_by: 1100000, rank: 7, popularity: 12,
    synopsis: 'Lelouch vi Britannia, exiled prince, receives the power of Geass and leads a rebellion against the empire that has conquered Japan.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 8, name: 'Drama' }, { mal_id: 3, name: 'Sci-Fi' }],
    year: 2006,
  },
  {
    mal_id: 31964,
    title: 'My Hero Academia',
    title_english: 'My Hero Academia',
    title_japanese: '僕のヒーローアカデミア',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-pGLxG8HKBM12.jpg',
    type: 'TV', source: 'Manga', episodes: 13, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 2016 – Jun 2016', from: '2016-04-03', to: '2016-06-26' },
    duration: '24 min per ep', rating: 'PG-13',
    score: 7.96, scored_by: 1700000, rank: 30, popularity: 6,
    synopsis: 'In a world where most people have superpowers, a Quirkless boy named Izuku Midoriya dreams of becoming a hero and inherits the power of the greatest hero.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 25, name: 'Shounen' }],
    year: 2016,
  },
  {
    mal_id: 1,
    title: 'Cowboy Bebop',
    title_english: 'Cowboy Bebop',
    title_japanese: 'カウボーイビバップ',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/4/19644.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/4/19644l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/4/19644.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/4/19644l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/1-T3PJUjFJyRMC.jpg',
    type: 'TV', source: 'Original', episodes: 26, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 1998 – Apr 1999', from: '1998-04-03', to: '1999-04-24' },
    duration: '24 min per ep', rating: 'R - 17+',
    score: 8.76, scored_by: 840000, rank: 4, popularity: 40,
    synopsis: 'A ragtag group of bounty hunters travel through space chasing criminals while dealing with their own haunted pasts.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 3, name: 'Sci-Fi' }],
    year: 1998,
  },
  {
    mal_id: 19815,
    title: 'No Game No Life',
    title_english: 'No Game No Life',
    title_japanese: 'ノーゲーム・ノーライフ',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1074/111944.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1074/111944l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1074/111944.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1074/111944l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/19815-yVQBqGOO7k34.jpg',
    type: 'TV', source: 'Light novel', episodes: 12, status: 'Finished Airing', airing: false,
    aired: { string: 'Apr 2014 – Jun 2014', from: '2014-04-09', to: '2014-06-25' },
    duration: '23 min per ep', rating: 'PG-13',
    score: 8.15, scored_by: 1500000, rank: 15, popularity: 13,
    synopsis: 'Siblings Sora and Shiro are unbeatable gamers who are summoned to a world where everything is decided by games.',
    genres: [{ mal_id: 5, name: 'Ecchi' }, { mal_id: 10, name: 'Fantasy' }, { mal_id: 29, name: 'Psychological' }],
    year: 2014,
  },
];

export const TOP_MOVIES_STATIC: StaticAnime[] = [
  {
    mal_id: 199,
    title: 'Sen to Chihiro no Kamikakushi',
    title_english: 'Spirited Away',
    title_japanese: '千と千尋の神隠し',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/6/79597.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/6/79597l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/6/79597.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/6/79597l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/199-4e5vEfONTN8t.jpg',
    type: 'Movie', source: 'Original', episodes: 1, status: 'Finished Airing', airing: false,
    aired: { string: 'Jul 2001', from: '2001-07-20', to: '2001-07-20' },
    duration: '2 hr 5 min', rating: 'PG',
    score: 8.86, scored_by: 720000, rank: 1, popularity: 15,
    synopsis: 'Ten-year-old Chihiro stumbles into a world ruled by gods, witches, and spirits, and begins her journey to free her parents and return to the human world.',
    genres: [{ mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    year: 2001,
  },
  {
    mal_id: 32281,
    title: 'Kimi no Na wa.',
    title_english: 'Your Name.',
    title_japanese: '君の名は。',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/5/87048.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/5/87048l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/5/87048.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/5/87048l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/99426-JOsMVMWtxSS5.jpg',
    type: 'Movie', source: 'Original', episodes: 1, status: 'Finished Airing', airing: false,
    aired: { string: 'Aug 2016', from: '2016-08-26', to: '2016-08-26' },
    duration: '1 hr 52 min', rating: 'PG',
    score: 8.83, scored_by: 1900000, rank: 2, popularity: 9,
    synopsis: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    genres: [{ mal_id: 8, name: 'Drama' }, { mal_id: 10, name: 'Fantasy' }, { mal_id: 22, name: 'Romance' }],
    year: 2016,
  },
  {
    mal_id: 43608,
    title: 'Demon Slayer Movie: Mugen Train',
    title_english: 'Demon Slayer: Kimetsu no Yaiba the Movie - Mugen Train',
    title_japanese: '劇場版「鬼滅の刃」無限列車編',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1704/106947.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1704/106947l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1704/106947.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1704/106947l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/120792-cxlBU9xS8SJT.jpg',
    type: 'Movie', source: 'Manga', episodes: 1, status: 'Finished Airing', airing: false,
    aired: { string: 'Oct 2020', from: '2020-10-16', to: '2020-10-16' },
    duration: '1 hr 57 min', rating: 'R - 17+',
    score: 8.31, scored_by: 860000, rank: 3, popularity: 11,
    synopsis: 'Tanjiro and his comrades board the Mugen Train on a new mission with the Flame Hashira, Rengoku Kyojuro.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 10, name: 'Fantasy' }],
    year: 2020,
  },
  {
    mal_id: 2251,
    title: 'Akira',
    title_english: 'Akira',
    title_japanese: 'AKIRA',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/7/148.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/7/148l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/7/148.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/7/148l.webp' },
    },
    type: 'Movie', source: 'Manga', episodes: 1, status: 'Finished Airing', airing: false,
    aired: { string: 'Jul 1988', from: '1988-07-16', to: '1988-07-16' },
    duration: '2 hr 4 min', rating: 'R - 17+',
    score: 8.1, scored_by: 300000, rank: 10, popularity: 55,
    synopsis: 'In 2019, a secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 3, name: 'Sci-Fi' }],
    year: 1988,
  },
  {
    mal_id: 38408,
    title: 'Koe no Katachi',
    title_english: 'A Silent Voice: The Movie',
    title_japanese: '聲の形',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg', large_image_url: 'https://cdn.myanimelist.net/images/anime/1122/96435l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/anime/1122/96435.webp', large_image_url: 'https://cdn.myanimelist.net/images/anime/1122/96435l.webp' },
    },
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-p9cHJSQGh1t9.jpg',
    type: 'Movie', source: 'Manga', episodes: 1, status: 'Finished Airing', airing: false,
    aired: { string: 'Sep 2016', from: '2016-09-17', to: '2016-09-17' },
    duration: '2 hr 10 min', rating: 'PG-13',
    score: 8.95, scored_by: 800000, rank: 4, popularity: 16,
    synopsis: 'A young man who bullied a deaf girl in elementary school sets out on a path of redemption to make things right.',
    genres: [{ mal_id: 8, name: 'Drama' }, { mal_id: 22, name: 'Romance' }],
    year: 2016,
  },
];

export const TOP_MANGA_STATIC = [
  {
    mal_id: 2,
    title: 'Berserk',
    title_english: 'Berserk',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/1/157897.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/1/157897l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/1/157897.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/1/157897l.webp' },
    },
    type: 'Manga', chapters: null, volumes: null, status: 'Publishing', publishing: true,
    score: 9.47, scored_by: 250000, rank: 1, popularity: 1,
    synopsis: 'Guts is a lone mercenary scarred by life, fighting demons and humans alike in a dark medieval world with cursed armor and a massive sword.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 8, name: 'Drama' }],
    authors: [{ name: 'Miura, Kentarou' }],
    published: { string: 'Aug 1989 – ?' },
    aired: null,
  },
  {
    mal_id: 1,
    title: 'Monster',
    title_english: 'Monster',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/3/258224.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/3/258224l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/3/258224.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/3/258224l.webp' },
    },
    type: 'Manga', chapters: 162, volumes: 18, status: 'Finished', publishing: false,
    score: 9.13, scored_by: 150000, rank: 2, popularity: 2,
    synopsis: 'A brilliant surgeon saves a mysterious boy\'s life, setting off a chain of events that will haunt him for years.',
    genres: [{ mal_id: 7, name: 'Mystery' }, { mal_id: 29, name: 'Psychological' }, { mal_id: 41, name: 'Thriller' }],
    authors: [{ name: 'Urasawa, Naoki' }],
    published: { string: 'Dec 1994 – Dec 2001' },
    aired: null,
  },
  {
    mal_id: 11977,
    title: 'Fullmetal Alchemist',
    title_english: 'Fullmetal Alchemist',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/3/243675.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/3/243675l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/3/243675.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/3/243675l.webp' },
    },
    type: 'Manga', chapters: 116, volumes: 27, status: 'Finished', publishing: false,
    score: 9.09, scored_by: 200000, rank: 3, popularity: 3,
    synopsis: 'Brothers Edward and Alphonse Elric seek the Philosopher\'s Stone to restore their bodies after a failed transmutation.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 10, name: 'Fantasy' }],
    authors: [{ name: 'Arakawa, Hiromu' }],
    published: { string: 'Jul 2001 – Jun 2010' },
    aired: null,
  },
  {
    mal_id: 656,
    title: 'Vagabond',
    title_english: 'Vagabond',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/1/259352.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/1/259352l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/1/259352.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/1/259352l.webp' },
    },
    type: 'Manga', chapters: 327, volumes: 37, status: 'On Hiatus', publishing: false,
    score: 9.15, scored_by: 135000, rank: 4, popularity: 4,
    synopsis: 'Miyamoto Musashi wanders Japan seeking to become the greatest swordsman alive, testing his steel against legendary rivals.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 8, name: 'Drama' }],
    authors: [{ name: 'Inoue, Takehiko' }],
    published: { string: 'Sep 1998 – ?' },
    aired: null,
  },
  {
    mal_id: 13,
    title: 'One Piece',
    title_english: 'One Piece',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/2/253146.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/2/253146l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/2/253146.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/2/253146l.webp' },
    },
    type: 'Manga', chapters: null, volumes: null, status: 'Publishing', publishing: true,
    score: 9.19, scored_by: 320000, rank: 5, popularity: 5,
    synopsis: 'Monkey D. Luffy sails with his pirate crew in search of the ultimate treasure to become King of the Pirates.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 4, name: 'Comedy' }],
    authors: [{ name: 'Oda, Eiichiro' }],
    published: { string: 'Jul 1997 – ?' },
    aired: null,
  },
  {
    mal_id: 21,
    title: 'Death Note',
    title_english: 'Death Note',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/2/54453.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/2/54453l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/2/54453.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/2/54453l.webp' },
    },
    type: 'Manga', chapters: 108, volumes: 12, status: 'Finished', publishing: false,
    score: 8.71, scored_by: 400000, rank: 7, popularity: 7,
    synopsis: 'An extraordinary story of a young man who uses a supernatural notebook to become god of a new world without crime.',
    genres: [{ mal_id: 7, name: 'Mystery' }, { mal_id: 29, name: 'Psychological' }, { mal_id: 41, name: 'Thriller' }],
    authors: [{ name: 'Ohba, Tsugumi' }],
    published: { string: 'Dec 2003 – May 2006' },
    aired: null,
  },
  {
    mal_id: 17517,
    title: 'Vinland Saga',
    title_english: 'Vinland Saga',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/2/188925.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/2/188925l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/2/188925.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/2/188925l.webp' },
    },
    type: 'Manga', chapters: 194, volumes: 27, status: 'Finished', publishing: false,
    score: 9.01, scored_by: 100000, rank: 6, popularity: 6,
    synopsis: 'Thorfinn, a young Viking warrior seeking revenge, eventually finds redemption in an age of conquest and violence.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 2, name: 'Adventure' }, { mal_id: 8, name: 'Drama' }],
    authors: [{ name: 'Yukimura, Makoto' }],
    published: { string: 'Apr 2005 – Sep 2023' },
    aired: null,
  },
  {
    mal_id: 23390,
    title: 'Tokyo Ghoul',
    title_english: 'Tokyo Ghoul',
    images: {
      jpg: { image_url: 'https://cdn.myanimelist.net/images/manga/3/134168.jpg', large_image_url: 'https://cdn.myanimelist.net/images/manga/3/134168l.jpg' },
      webp: { image_url: 'https://cdn.myanimelist.net/images/manga/3/134168.webp', large_image_url: 'https://cdn.myanimelist.net/images/manga/3/134168l.webp' },
    },
    type: 'Manga', chapters: 143, volumes: 14, status: 'Finished', publishing: false,
    score: 8.07, scored_by: 300000, rank: 8, popularity: 8,
    synopsis: 'Tokyo is haunted by "ghouls" who look like regular people but feed on human flesh. A normal student becomes one after a fateful meeting.',
    genres: [{ mal_id: 1, name: 'Action' }, { mal_id: 8, name: 'Drama' }, { mal_id: 26, name: 'Horror' }],
    authors: [{ name: 'Ishida, Sui' }],
    published: { string: 'Sep 2011 – Sep 2014' },
    aired: null,
  },
];

// Hero spotlight — 7 premium anime with high-quality banner images (Kitsu CDN)
export const HERO_SPOTLIGHT_ANIME = [
  {
    mal_id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    fanartUrl: 'https://media.kitsu.app/anime/cover_images/3936/original.jpg',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/1223/96541l.jpg',
    genres: [{ name: 'Action' }, { name: 'Adventure' }, { name: 'Drama' }, { name: 'Fantasy' }],
    synopsis: 'Two brothers search for a Philosopher\'s Stone after an attempt to revive their deceased mother goes awry, leaving them in damaged physical forms.',
    score: 9.11, status: 'Finished', type: 'TV', year: 2009,
  },
  {
    mal_id: 1535,
    title: 'Death Note',
    fanartUrl: 'https://media.kitsu.app/anime/cover_images/1376/original.jpg',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/9/9453l.jpg',
    genres: [{ name: 'Psychological' }, { name: 'Mystery' }, { name: 'Supernatural' }],
    synopsis: 'A high school student discovers a supernatural notebook that lets him kill anyone whose name he writes in it. He sets out to create a perfect world — but at what cost?',
    score: 8.62, status: 'Finished', type: 'TV', year: 2006,
  },
  {
    mal_id: 16498,
    title: 'Attack on Titan',
    fanartUrl: 'https://media.kitsu.app/anime/cover_images/7442/original.png',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
    genres: [{ name: 'Action' }, { name: 'Drama' }, { name: 'Fantasy' }],
    synopsis: 'Eren Yeager swears to destroy the Titans after his mother is devoured. He joins the military and uncovers the shocking truth about their walled world.',
    score: 8.53, status: 'Finished', type: 'TV', year: 2013,
  },
  {
    mal_id: 11061,
    title: 'Hunter x Hunter (2011)',
    fanartUrl: 'https://media.kitsu.app/anime/cover_images/6448/original.jpg',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg',
    genres: [{ name: 'Action' }, { name: 'Adventure' }, { name: 'Fantasy' }],
    synopsis: 'Gon Freecss aspires to become a Hunter to find his missing father. He navigates a world of danger, friendship, and the darkest corners of human nature.',
    score: 9.04, status: 'Finished', type: 'TV', year: 2011,
  },
  {
    mal_id: 9253,
    title: 'Steins;Gate',
    fanartUrl: 'https://media.kitsu.app/anime/cover_images/5646/original.jpg',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/5/73199l.jpg',
    genres: [{ name: 'Sci-Fi' }, { name: 'Psychological' }, { name: 'Thriller' }],
    synopsis: 'A self-proclaimed mad scientist accidentally invents a way to send messages to the past, entangling himself in a dangerous web of time travel and consequences.',
    score: 9.07, status: 'Finished', type: 'TV', year: 2011,
  },
  {
    mal_id: 40748,
    title: 'Jujutsu Kaisen',
    fanartUrl: 'https://media.kitsu.app/anime/cover_images/42765/original.jpeg',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
    genres: [{ name: 'Action' }, { name: 'Fantasy' }, { name: 'Shounen' }],
    synopsis: 'After swallowing a cursed talisman, Yuji Itadori joins a secret organization of sorcerers to kill a powerful Cursed Spirit named Ryomen Sukuna.',
    score: 8.72, status: 'Finished', type: 'TV', year: 2020,
  },
  {
    mal_id: 38000,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    fanartUrl: 'https://media.kitsu.app/anime/41370/cover_image/7958f9c01b57c980636386d124553791.jpg',
    coverUrl: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
    genres: [{ name: 'Action' }, { name: 'Fantasy' }, { name: 'Shounen' }],
    synopsis: 'Tanjiro becomes a demon slayer after his family is slaughtered and his sister Nezuko is turned into a demon. A breathtaking tale of family and perseverance.',
    score: 8.57, status: 'Finished', type: 'TV', year: 2019,
  },
];
